spring:
  application:
    name: exercise.spring.boot
  datasource:
    url: jdbc:mysql://localhost:3306/exercise.spring.boot?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!
  jpa:
    show-sql: true
